<form action="">
                    <label for="title">Danh xưng*</label>
                    <select id="title" name="title" required>
                        <option value="">Vui lòng chọn</option>
                        <option value="mr">Anh</option>
                        <option value="ms">Chị</option>
                    </select> <br>
                    <label for="name">Tên*</label>
                    <input type="text" required> <br>
                    <label for="name">Họ*</label>
                    <input type="text" required> <br>
                    <label for="number">Số điện thoại*</label>
                    <input type="number"> <br>
                    <label for="email">Email*</label>
                    <input type="text" required> <br>
                    <label for="province">Thành phố/Tỉnh*</label>
                    <select id="province" name="province" required>
                        <option value="">Vui lòng chọn</option>
                        <option value="TP. Hồ Chí Minh">Hồ Chí Minh</option>
                        <option value="Hà Nội">Hà Nội</option>
                        <option value="Điện Biên">Điện Biên</option>
                        <option value="Hòa Bình">Hòa Bình</option>
                        <option value="Lai Châu">Lai Châu</option>
                        <option value="Sơn La">Sơn La</option>
                        <option value="HCM">Hà Giang</option>
                        <option value="HCM">Cao Bằng</option>
                        <option value="HCM">Bắc Kạn</option>
                        <option value="HCM">Lạng Sơn</option>
                        <option value="HCM">Tuyên Quang</option>
                        <option value="HCM">Thái Nguyên</option>
                        <option value="HCM">Phú Thọ</option>
                        <option value="HCM">Bắc Giang</option>
                        <option value="HCM">Quảng Ninh</option>
                        <option value="HCM">Bắc Ninh</option>
                        <option value="HCM">Ninh Bình</option>
                        <option value="HCM">Hà Nam</option>
                        <option value="HCM">Lào Cai</option>
                        <option value="HCM">Hải Dương</option>
                        <option value="HCM">Hải Phòng</option>
                        <option value="HCM">Hưng Yên</option>
                        <option value="HCM">Nam Định</option>
                        <option value="HCM">Thái Bình</option>
                        <option value="HCM">Vĩnh Phúc</option>
                        <option value="HCM">Thanh Hóa</option>
                        <option value="HCM">Nghệ An</option>
                        <option value="HCM">Vinh</option>
                        <option value="HCM">Hà Tĩnh</option>
                        <option value="HCM">Quảng Bình</option>
                        <option value="HCM">Quảng Trị</option>
                        <option value="HCM">Thừa Thiên Huế</option>
                        <option value="HCM">Đà Nẵng</option>
                        <option value="HCM">Quảng Nam</option>
                        <option value="HCM">Quảng Ngãi</option>
                        <option value="HCM">Bình Định</option>
                        <option value="HCM">Quảng Ngãi</option>
                        <option value="HCM">Phú Yên</option>
                        <option value="HCM">Yên Bái</option>
                        <option value="HCM">Gia Lai</option>
                        <option value="HCM">Khánh Hòa</option>
                        <option value="HCM">Ninh Thuận</option>
                        <option value="HCM">Đắk Lắk</option>
                        <option value="HCM">Đắk Nông</option>
                        <option value="HCM">Lâm Đồng</option>
                        <option value="HCM">Bình Dương</option>
                        <option value="HCM">Bình Phước</option>
                        <option value="HCM">Tây Ninh</option>
                        <option value="HCM">Đồng Nai</option>
                        <option value="HCM">Bà Rịa Vũng Tàu</option>
                        <option value="HCM">Cần Thơ</option>
                        <option value="HCM">Long An</option>
                        <option value="HCM">An Giang</option>
                        <option value="HCM">Đồng Tháp</option>
                        <option value="HCM">Tiền Giang</option>
                        <option value="HCM">Bến Tre</option>
                        <option value="HCM">Vĩnh Long</option>
                        <option value="HCM">Trà Vinh</option>
                        <option value="HCM">Hậu Giang</option>
                        <option value="HCM">Kiên Giang</option>
                        <option value="HCM">Sóc Trăng</option>
                        <option value="HCM">Bạc Liêu</option>
                        <option value="HCM">Cà Mau</option>
                        <option value="HCM">Kon Tum</option>
                    </select> <br>
                    <label for="district">Quận/Huyện:</label>
                    <select id="district" name="district" required>
                        <option value="">Chọn quận/huyện</option>
                    </select> <br>
                    <label for="type">Mẫu xe muốn lái thử*</label>
                    <select id="type" name="type" required>
                        <option value="">Vui lòng chọn</option>
                        <option value="BMW 3 Series Sedan">BMW 3 Series Sedan</option>
                        <option value="BMW 4 Series Convertible">BMW 4 Series Convertible</option>
                        <option value="BMW 4 Series Gran Coupé">BMW 4 Series Gran Coupé</option>
                        <option value="BMW 5 Series Sedan">BMW 5 Series Sedan</option>
                        <option value="BMW 7 Series Sedan">BMW 7 Series Sedan</option>
                        <option value="BMW 8 Series Gran Coupé">BMW 8 Series Gran Coupé</option>
                        <option value="BMW X3 Serie">BMW X3 Series</option>
                        <option value="BMW X5 Series">BMW X5 Series</option>
                        <option value="BMW X6 Series">BMW X6 Series</option>
                        <option value="BMW X7 Serie">BMW X7 Series</option>
                        <option value="BMW XM Series">BMW XM Series</option>
                        <option value="BMW iX3">BMW iX3</option>
                        <option value="BMW i4 Gran Coupé">BMW i4 Gran Coupé</option>
                        <option value="BMW i7">BMW i7</option>
                        <option value="BMW Z4">BMW Z4</option>
                    </select> <br>
                </form>