CREATE TABLE huyen (
    mahuyen INT NOT NULL AUTO_INCREMENT,
    tenhuyen1 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    tenhuyen2 varchar(255) NOT NULL,
    matinh INT,
    PRIMARY KEY (mahuyen),
    FOREIGN KEY (matinh) REFERENCES tinh(matinh)
);

INSERT INTO huyen ()

CREATE TABLE tinh (
    matinh 
    tentinh varchar(255) NOT NULL,
    PRIMARY KEY (matinh),
);

INSERT INTRO tinh (tentinh, mahuyen, maxa_phuong) VALUE 
    ('An Giang'),
    ('Bà Rịa – Vũng Tàu'),
    ('Bạc Liêu'),
    ('Bắc Giang'),
    ('Bắc Kạn'),
    ('Bắc Ninh'),
    ('Bến Tre'),
    ('Bình Dương'),
    ('Bình Định'),
    ('Nghệ An'),
    ('Ninh Thuận'),
    ('Quảng Trị'),
    ('Thái Bình'),
    ('Tiền Giang'),
    ('Vĩnh Phúc'),
    ('Bình Phước'),
    ('Bình Thuận'),
    ('Cà Mau'),
    ('Cao Bằng'),
    ('TP Hồ Chí Minh'),
    ('Đắk Lắk'),
    ('Đắk Nông'),
    ('Điện Biên'),
    ('Đồng Nai'),
    ('Đồng Tháp'),
    ('Phú Thọ'),
    ('Phú Yên'),
    ('Sóc Trăng'),
    ('Thái Nguyên'),
    ('Trà Vinh'),
    ('Yên Bái'),
    ('Gia Lai'),
    ('Hà Giang'),
    ('Hà Nam'),
    ('Hà Tĩnh'),
    ('Hải Dương'),
    ('Hậu Giang'),
    ('Hà Nội'),
    ('Hòa Bình'),
    ('Hưng Yên'),
    ('Khánh Hòa'),
    ('Quảng Bình'),
    ('Quảng Nam'),
    ('Sơn La'),
    ('Thanh Hóa'),
    ('Tuyên Quang'),
    ('Kiên Giang'),
    ('Kon Tum'),
    ('Lai Châu'),
    ('Lạng Sơn'),
    ('Lào Cai'),
    ('Lâm Đồng'),
    ('Nam Định'),
    ('Long An'),
    ('Ninh Bình'),
    ('Quảng Ngãi'),
    ('Quảng Ninh'),
    ('Tây Ninh'),
    ('Thừa Thiên Huế'),
    ('Vĩnh Long'),
    